apiVersion: v1
kind: LimitRange
metadata:
  name: ephemeral-storage-limit-range
  namespace: rook-ceph
spec:
  limits:
  - default:
      ephemeral-storage: 2Gi
    defaultRequest:
      ephemeral-storage: 130Mi
    type: Container
